"""Self-contained HTML pacing reports.

:func:`render_report` turns a :class:`~monteur.analysis.PacingStats` into one
HTML document with inline CSS and inline SVG charts — no external requests,
no scripts. :func:`save_report` writes it to disk as UTF-8.
"""

from __future__ import annotations

import html
from pathlib import Path

from monteur import __version__
from monteur.analysis import PacingStats, Section, Shot

_EMPTY_STATE_MESSAGE = "No shots to analyze — this timeline has no cuts to report on."

_TIME_STEPS = (1.0, 2.0, 5.0, 10.0, 15.0, 30.0, 60.0, 120.0, 300.0, 600.0, 900.0, 1800.0, 3600.0, 7200.0)
_VALUE_STEPS = (0.1, 0.2, 0.25, 0.5, 1.0, 2.0, 5.0, 10.0, 20.0, 30.0, 60.0, 120.0)

_CURVE_W, _CURVE_H = 760.0, 280.0
_HIST_W, _HIST_H = 760.0, 240.0
_STRIP_W, _STRIP_H = 760.0, 32.0


def render_report(stats: PacingStats, compare_to: PacingStats | None = None, title: str = "") -> str:
    heading = title or stats.timeline_name
    doc_title = title or f"{stats.timeline_name} — Monteur pacing report"
    parts: list[str] = [_header_html(stats, heading)]
    if stats.shot_count <= 0:
        parts.append(f'<section class="card empty-state"><p>{_esc(_EMPTY_STATE_MESSAGE)}</p></section>')
    else:
        parts.append(_tiles_html(stats, compare_to))
        parts.append(_curve_card(stats, compare_to))
        parts.append(_sections_card(stats))
        parts.append(_histogram_card(stats))
        parts.append(_longest_card(stats))
    parts.append(_footer_html())
    return _page(doc_title, "\n".join(parts))


def save_report(
    stats: PacingStats,
    path: str | Path,
    compare_to: PacingStats | None = None,
    title: str = "",
) -> None:
    Path(path).write_text(render_report(stats, compare_to=compare_to, title=title), encoding="utf-8")


def _esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def _num(value: float) -> str:
    return f"{value:.1f}"


def _fmt_clock(seconds: float) -> str:
    total = int(round(max(seconds, 0.0)))
    hours, rem = divmod(total, 3600)
    minutes, secs = divmod(rem, 60)
    if hours:
        return f"{hours}:{minutes:02d}:{secs:02d}"
    return f"{minutes}:{secs:02d}"


def _fmt_secs(seconds: float) -> str:
    return f"{seconds:.1f}s"


def _fmt_fps(fps: float) -> str:
    return f"{fps:g} fps"


def _tick_values(span: float, candidates: tuple[float, ...], max_ticks: int = 7) -> list[float]:
    if span <= 0:
        return []
    step = candidates[-1]
    for candidate in candidates:
        if span / candidate <= max_ticks:
            step = candidate
            break
    ticks: list[float] = []
    value = step
    while value <= span + step * 1e-6:
        ticks.append(value)
        value += step
    return ticks


def _header_html(stats: PacingStats, heading: str) -> str:
    meta = " · ".join(
        (
            _esc(stats.timeline_name),
            _esc(_fmt_clock(stats.duration_seconds)),
            _esc(_fmt_fps(stats.fps)),
        )
    )
    return (
        '<header class="report-header">'
        '<p class="eyebrow">Monteur pacing report</p>'
        f"<h1>{_esc(heading)}</h1>"
        f'<p class="meta">{meta}</p>'
        "</header>"
    )


def _footer_html() -> str:
    return f'<footer class="report-footer">Generated by Monteur v{_esc(__version__)}</footer>'


def _tile(label: str, value: str, compare_value: str | None) -> str:
    delta = ""
    if compare_value is not None:
        delta = f'<div class="tile-delta">{_esc(value)} &rarr; {_esc(compare_value)}</div>'
    return (
        '<div class="tile">'
        f'<div class="tile-label">{_esc(label)}</div>'
        f'<div class="tile-value">{_esc(value)}</div>'
        f"{delta}"
        "</div>"
    )


def _tiles_html(stats: PacingStats, compare_to: PacingStats | None) -> str:
    rows: list[tuple[str, str, str | None]] = [
        ("Shots", str(stats.shot_count), str(compare_to.shot_count) if compare_to else None),
        ("Cuts", str(stats.cut_count), str(compare_to.cut_count) if compare_to else None),
        (
            "Average shot (ASL)",
            _fmt_secs(stats.avg_shot_seconds),
            _fmt_secs(compare_to.avg_shot_seconds) if compare_to else None,
        ),
        (
            "Median shot",
            _fmt_secs(stats.median_shot_seconds),
            _fmt_secs(compare_to.median_shot_seconds) if compare_to else None,
        ),
        (
            "Std deviation",
            _fmt_secs(stats.std_shot_seconds),
            _fmt_secs(compare_to.std_shot_seconds) if compare_to else None,
        ),
        (
            "Longest shot",
            _fmt_secs(stats.max_shot_seconds),
            _fmt_secs(compare_to.max_shot_seconds) if compare_to else None,
        ),
        (
            "Shortest shot",
            _fmt_secs(stats.min_shot_seconds),
            _fmt_secs(compare_to.min_shot_seconds) if compare_to else None,
        ),
    ]
    tiles = "".join(_tile(label, value, other) for label, value, other in rows)
    return f'<section class="tiles">{tiles}</section>'


def _curve_card(stats: PacingStats, compare_to: PacingStats | None) -> str:
    if not stats.pacing_curve:
        body = '<p class="chart-note">No pacing-curve data available.</p>'
        return _card("Pacing curve", body)
    legend = ""
    if compare_to is not None:
        legend = (
            '<div class="legend">'
            f'<span class="key"><span class="swatch" style="background:var(--series-1)"></span>{_esc(stats.timeline_name)}</span>'
            f'<span class="key"><span class="swatch" style="background:var(--series-2)"></span>{_esc(compare_to.timeline_name)}</span>'
            "</div>"
        )
    svg = _curve_svg(stats, compare_to)
    return _card("Pacing curve", legend + svg, "Rolling average shot length across the timeline")


def _curve_svg(stats: PacingStats, compare_to: PacingStats | None) -> str:
    ml, mr, mt, mb = 48.0, 16.0, 14.0, 34.0
    plot_w = _CURVE_W - ml - mr
    plot_h = _CURVE_H - mt - mb

    series: list[tuple[str, str, list[tuple[float, float]]]] = [
        ("var(--series-1)", stats.timeline_name, stats.pacing_curve)
    ]
    if compare_to is not None and compare_to.pacing_curve:
        series.append(("var(--series-2)", compare_to.timeline_name, compare_to.pacing_curve))

    xmax = max(
        [stats.duration_seconds]
        + ([compare_to.duration_seconds] if compare_to else [])
        + [p[0] for _, _, curve in series for p in curve]
    )
    xmax = xmax if xmax > 0 else 1.0
    peak = max([p[1] for _, _, curve in series for p in curve] + [stats.avg_shot_seconds])
    ymax = peak * 1.15 if peak > 0 else 1.0

    def sx(seconds: float) -> float:
        return ml + seconds / xmax * plot_w

    def sy(value: float) -> float:
        return mt + plot_h - min(value, ymax) / ymax * plot_h

    baseline = mt + plot_h
    out: list[str] = []
    for tick in _tick_values(ymax, _VALUE_STEPS, max_ticks=5):
        y = sy(tick)
        out.append(f'<line x1="{_num(ml)}" y1="{_num(y)}" x2="{_num(ml + plot_w)}" y2="{_num(y)}" stroke="var(--grid)" stroke-width="1"/>')
        out.append(f'<text x="{_num(ml - 8)}" y="{_num(y + 3.5)}" text-anchor="end" class="axis">{_esc(f"{tick:g}s")}</text>')
    out.append(f'<line x1="{_num(ml)}" y1="{_num(baseline)}" x2="{_num(ml + plot_w)}" y2="{_num(baseline)}" stroke="var(--axis)" stroke-width="1"/>')
    for tick in _tick_values(xmax, _TIME_STEPS):
        x = sx(tick)
        out.append(f'<line x1="{_num(x)}" y1="{_num(baseline)}" x2="{_num(x)}" y2="{_num(baseline + 4)}" stroke="var(--axis)" stroke-width="1"/>')
        out.append(f'<text x="{_num(x)}" y="{_num(baseline + 18)}" text-anchor="middle" class="axis">{_esc(_fmt_clock(tick))}</text>')

    primary_color, _, primary_curve = series[0]
    area_d = (
        f"M{_num(sx(primary_curve[0][0]))} {_num(baseline)} "
        + " ".join(f"L{_num(sx(px))} {_num(sy(py))}" for px, py in primary_curve)
        + f" L{_num(sx(primary_curve[-1][0]))} {_num(baseline)} Z"
    )
    out.append(f'<path d="{area_d}" fill="{primary_color}" opacity="0.1"/>')

    if stats.avg_shot_seconds > 0:
        ref_y = sy(stats.avg_shot_seconds)
        out.append(
            f'<line x1="{_num(ml)}" y1="{_num(ref_y)}" x2="{_num(ml + plot_w)}" y2="{_num(ref_y)}" '
            'stroke="var(--ink-muted)" stroke-width="1" stroke-dasharray="4 3"/>'
        )
        out.append(
            f'<text x="{_num(ml + plot_w)}" y="{_num(ref_y - 5)}" text-anchor="end" class="axis">'
            f"avg {_esc(_fmt_secs(stats.avg_shot_seconds))}</text>"
        )

    for color, name, curve in series:
        pts = " ".join(f"{_num(sx(px))},{_num(sy(py))}" for px, py in curve)
        out.append(
            f'<polyline points="{pts}" fill="none" stroke="{color}" stroke-width="2" '
            'stroke-linejoin="round" stroke-linecap="round"/>'
        )
        end_x, end_y = curve[-1]
        out.append(
            f'<circle cx="{_num(sx(end_x))}" cy="{_num(sy(end_y))}" r="4" fill="{color}" '
            'stroke="var(--surface)" stroke-width="2"/>'
        )
        for px, py in curve:
            tip = f"{name} · {_fmt_clock(px)} · rolling avg {_fmt_secs(py)}"
            out.append(
                f'<circle cx="{_num(sx(px))}" cy="{_num(sy(py))}" r="8" fill="transparent">'
                f"<title>{_esc(tip)}</title></circle>"
            )
    label = f"Pacing curve for {stats.timeline_name}"
    return _svg(_CURVE_W, _CURVE_H, label, "".join(out))


def _sections_card(stats: PacingStats) -> str:
    if not stats.sections:
        return _card("Tempo sections", '<p class="chart-note">No section data available.</p>')
    legend = (
        '<div class="legend">'
        '<span class="key"><span class="swatch" style="background:var(--tempo-fast)"></span>Fast</span>'
        '<span class="key"><span class="swatch" style="background:var(--tempo-medium)"></span>Medium</span>'
        '<span class="key"><span class="swatch" style="background:var(--tempo-slow)"></span>Slow</span>'
        "</div>"
    )
    return _card(
        "Tempo sections",
        _sections_svg(stats.sections, stats.duration_seconds) + legend,
        "Fast, medium and slow stretches relative to the cut's own average tempo",
    )


def _sections_svg(sections: list[Section], duration: float) -> str:
    total = max([duration] + [s.end for s in sections])
    total = total if total > 0 else 1.0
    out: list[str] = []
    last = len(sections) - 1
    for i, section in enumerate(sections):
        x0 = section.start / total * _STRIP_W
        x1 = section.end / total * _STRIP_W
        width = max(x1 - x0 - (0.0 if i == last else 2.0), 1.0)
        color = f"var(--tempo-{section.label})" if section.label in ("fast", "medium", "slow") else "var(--tempo-medium)"
        tip = (
            f"{section.label} · {_fmt_clock(section.start)}–{_fmt_clock(section.end)}"
            f" · avg shot {_fmt_secs(section.avg_shot_length)}"
        )
        out.append(
            f'<g><rect x="{_num(x0)}" y="4" width="{_num(width)}" height="24" rx="2" fill="{color}"/>'
            f"<title>{_esc(tip)}</title></g>"
        )
    return _svg(_STRIP_W, _STRIP_H, "Tempo sections across the timeline", "".join(out))


def _histogram_card(stats: PacingStats) -> str:
    if not stats.histogram:
        return _card("Shot-length histogram", '<p class="chart-note">No histogram data available.</p>')
    return _card(
        "Shot-length histogram",
        _histogram_svg(stats.histogram),
        "How many shots fall into each length bucket",
    )


def _histogram_svg(histogram: list[tuple[str, int]]) -> str:
    ml, mr, mt, mb = 36.0, 12.0, 20.0, 30.0
    plot_w = _HIST_W - ml - mr
    plot_h = _HIST_H - mt - mb
    baseline = mt + plot_h
    max_count = max((count for _, count in histogram), default=0)
    ymax = float(max_count) if max_count > 0 else 1.0
    slot_w = plot_w / len(histogram)
    bar_w = min(24.0, slot_w * 0.6)

    out: list[str] = []
    for tick in _tick_values(ymax, _VALUE_STEPS, max_ticks=4):
        if tick != int(tick):
            continue
        y = baseline - tick / ymax * plot_h
        out.append(f'<line x1="{_num(ml)}" y1="{_num(y)}" x2="{_num(ml + plot_w)}" y2="{_num(y)}" stroke="var(--grid)" stroke-width="1"/>')
        out.append(f'<text x="{_num(ml - 8)}" y="{_num(y + 3.5)}" text-anchor="end" class="axis">{int(tick)}</text>')
    out.append(f'<line x1="{_num(ml)}" y1="{_num(baseline)}" x2="{_num(ml + plot_w)}" y2="{_num(baseline)}" stroke="var(--axis)" stroke-width="1"/>')

    for i, (label, count) in enumerate(histogram):
        cx = ml + slot_w * (i + 0.5)
        x0 = cx - bar_w / 2
        out.append(f'<text x="{_num(cx)}" y="{_num(baseline + 18)}" text-anchor="middle" class="axis">{_esc(label)}</text>')
        tip = f"{label} · {count} shot{'s' if count != 1 else ''}"
        if count > 0:
            y_top = baseline - count / ymax * plot_h
            out.append(f"<g>{_bar_path(x0, y_top, bar_w, baseline)}<title>{_esc(tip)}</title></g>")
            out.append(f'<text x="{_num(cx)}" y="{_num(y_top - 6)}" text-anchor="middle" class="axis">{count}</text>')
        else:
            out.append(f'<text x="{_num(cx)}" y="{_num(baseline - 6)}" text-anchor="middle" class="axis">0</text>')
    return _svg(_HIST_W, _HIST_H, "Shot-length histogram", "".join(out))


def _bar_path(x: float, y_top: float, width: float, y_base: float, radius: float = 4.0) -> str:
    height = y_base - y_top
    if height < radius + 1 or width < radius * 2 + 2:
        return (
            f'<rect x="{_num(x)}" y="{_num(y_top)}" width="{_num(width)}" '
            f'height="{_num(max(height, 0.0))}" fill="var(--series-1)"/>'
        )
    return (
        f'<path d="M{_num(x)} {_num(y_base)} V{_num(y_top + radius)} '
        f"Q{_num(x)} {_num(y_top)} {_num(x + radius)} {_num(y_top)} "
        f"H{_num(x + width - radius)} "
        f"Q{_num(x + width)} {_num(y_top)} {_num(x + width)} {_num(y_top + radius)} "
        f'V{_num(y_base)} Z" fill="var(--series-1)"/>'
    )


def _longest_card(stats: PacingStats) -> str:
    if not stats.longest_shots:
        return _card("Longest shots", '<p class="chart-note">No shot data available.</p>')
    rows = "".join(_longest_row(shot) for shot in stats.longest_shots)
    table = (
        '<table class="shots-table">'
        "<thead><tr><th>Shot</th><th>Position</th><th>Length</th></tr></thead>"
        f"<tbody>{rows}</tbody></table>"
    )
    return _card("Longest shots", table)


def _longest_row(shot: Shot) -> str:
    return (
        f"<tr><td>{_esc(shot.name)}</td>"
        f'<td class="num">{_esc(_fmt_clock(shot.start))}</td>'
        f'<td class="num">{_esc(_fmt_secs(shot.length))}</td></tr>'
    )


def _card(title: str, body: str, subtitle: str = "") -> str:
    sub = f'<p class="card-sub">{_esc(subtitle)}</p>' if subtitle else ""
    return f'<section class="card"><h2>{_esc(title)}</h2>{sub}{body}</section>'


def _svg(width: float, height: float, label: str, body: str) -> str:
    return (
        f'<svg viewBox="0 0 {width:g} {height:g}" width="100%" role="img" '
        f'aria-label="{_esc(label)}" xmlns="http://www.w3.org/2000/svg">{body}</svg>'
    )


def _page(doc_title: str, body: str) -> str:
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n<head>\n<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f"<title>{_esc(doc_title)}</title>\n"
        f"<style>{_CSS}</style>\n</head>\n<body>\n"
        f'<main class="report">\n{body}\n</main>\n</body>\n</html>\n'
    )


_CSS = """
:root {
  --page: #f9f9f7;
  --surface: #fcfcfb;
  --ink: #0b0b0b;
  --ink-2: #52514e;
  --ink-muted: #898781;
  --grid: #e1e0d9;
  --axis: #c3c2b7;
  --border: rgba(11, 11, 11, 0.10);
  --series-1: #2a78d6;
  --series-2: #1baf7a;
  --tempo-fast: #0d366b;
  --tempo-medium: #2a78d6;
  --tempo-slow: #86b6ef;
}
@media (prefers-color-scheme: dark) {
  :root {
    --page: #0d0d0d;
    --surface: #1a1a19;
    --ink: #ffffff;
    --ink-2: #c3c2b7;
    --ink-muted: #898781;
    --grid: #2c2c2a;
    --axis: #383835;
    --border: rgba(255, 255, 255, 0.10);
    --series-1: #3987e5;
    --series-2: #199e70;
    --tempo-fast: #9ec5f4;
    --tempo-medium: #3987e5;
    --tempo-slow: #184f95;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--page);
  color: var(--ink);
  font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
  line-height: 1.45;
}
.report { max-width: 840px; margin: 0 auto; padding: 32px 20px 48px; }
.report-header { margin-bottom: 20px; }
.eyebrow {
  margin: 0 0 4px;
  font-size: 12px;
  font-weight: 600;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--ink-muted);
}
h1 { margin: 0 0 6px; font-size: 26px; font-weight: 650; }
.meta { margin: 0; color: var(--ink-2); font-size: 14px; }
.tiles {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
  gap: 12px;
  margin-bottom: 20px;
}
.tile, .card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 10px;
}
.tile { padding: 12px 14px; }
.tile-label { font-size: 12px; color: var(--ink-2); margin-bottom: 4px; }
.tile-value { font-size: 22px; font-weight: 600; }
.tile-delta { font-size: 12px; color: var(--ink-2); margin-top: 4px; }
.card { padding: 16px 18px 14px; margin-bottom: 20px; }
.card h2 { margin: 0 0 2px; font-size: 15px; font-weight: 650; }
.card-sub { margin: 0 0 12px; font-size: 13px; color: var(--ink-2); }
.chart-note { margin: 8px 0 4px; font-size: 13px; color: var(--ink-muted); }
.empty-state { padding: 40px 24px; text-align: center; }
.empty-state p { margin: 0; color: var(--ink-2); font-size: 15px; }
svg { display: block; height: auto; }
svg text.axis {
  font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
  font-size: 11px;
  font-variant-numeric: tabular-nums;
  fill: var(--ink-muted);
}
.legend { display: flex; gap: 16px; flex-wrap: wrap; margin: 8px 0 6px; font-size: 13px; color: var(--ink-2); }
.key { display: inline-flex; align-items: center; gap: 6px; }
.swatch { width: 10px; height: 10px; border-radius: 3px; display: inline-block; }
.shots-table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 14px; }
.shots-table th {
  text-align: left;
  font-size: 12px;
  font-weight: 600;
  color: var(--ink-2);
  padding: 6px 10px;
  border-bottom: 1px solid var(--grid);
}
.shots-table td { padding: 7px 10px; border-bottom: 1px solid var(--grid); }
.shots-table tr:last-child td { border-bottom: none; }
.shots-table td.num, .shots-table th.num { font-variant-numeric: tabular-nums; }
.report-footer { margin-top: 8px; font-size: 12px; color: var(--ink-muted); text-align: center; }
"""
