"""Tests for monteur.preview — the no-Resolve preview renderer.

End-to-end against the synthetic demo footage (tests/.demo-footage,
generated by make_demo_footage.py; skipped when missing) plus pure
validation tests that need neither footage nor ffmpeg.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import pytest

from _demo import DEMO
from monteur.media import MonteurMediaError, probe
from monteur.montage import MontageEntry, MontagePlan
from monteur import preview
from monteur.preview import extract_thumbnail, render_preview

try:
    import imageio_ffmpeg  # noqa: F401

    HAVE_FFMPEG = True
except ImportError:
    import shutil as _shutil

    HAVE_FFMPEG = bool(_shutil.which("ffmpeg"))

needs_ffmpeg = pytest.mark.skipif(not HAVE_FFMPEG, reason="ffmpeg not available")
needs_demo = pytest.mark.skipif(
    not (DEMO / "clip_A.mp4").exists(), reason="demo footage not present"
)


def demo_plan(music: bool = True) -> MontagePlan:
    """A tiny 6 s plan: three entries with a 0.4 s record gap (black dip)."""
    entries = [
        MontageEntry(
            clip_path=str(DEMO / "clip_A.mp4"),
            source_start=1.0, source_end=3.0,
            record_start=0.0, record_end=2.0, score=1.0,
        ),
        # record gap 2.0..2.4 — the smash-to-black dip
        MontageEntry(
            clip_path=str(DEMO / "clip_C.mp4"),
            source_start=2.0, source_end=4.0,
            record_start=2.4, record_end=4.4, score=0.9,
        ),
        MontageEntry(
            clip_path=str(DEMO / "clip_D.mp4"),
            source_start=0.5, source_end=2.1,
            record_start=4.4, record_end=6.0, score=0.8,
        ),
    ]
    return MontagePlan(
        music_path=str(DEMO / "song.wav") if music else "",
        duration=6.0,
        music_start=8.0 if music else 0.0,
        song_duration=60.0 if music else 0.0,
        fade_in=0.2,
        fade_out=0.5,
        entries=entries,
        dips=[(2.0, 0.4)],
    )


# ------------------------------------------------------------ validation


def test_unknown_audio_mode_raises():
    with pytest.raises(ValueError, match="unknown audio mode"):
        render_preview(demo_plan(), "out.mp4", audio="karaoke")


@pytest.mark.parametrize("mode", ["music", "mix"])
def test_music_modes_without_music_raise(mode):
    with pytest.raises(ValueError, match="plan has no music"):
        render_preview(demo_plan(music=False), "out.mp4", audio=mode)


def test_empty_plan_raises():
    plan = MontagePlan(music_path=str(DEMO / "song.wav"), duration=6.0)
    with pytest.raises(ValueError, match="no entries"):
        render_preview(plan, "out.mp4")


# ------------------------------------------------------------ rendering


@needs_ffmpeg
@needs_demo
def test_render_preview_music_mode(tmp_path):
    out = tmp_path / "preview.mp4"
    result = render_preview(demo_plan(), str(out), width=640, audio="music")
    assert out.is_file() and out.stat().st_size > 0
    assert result["path"] == str(out)
    assert result["segments"] == 4  # 3 entries + 1 black dip
    assert result["width"] == 640
    info = probe(out)
    assert info.duration == pytest.approx(6.0, abs=0.3)
    assert result["duration"] == pytest.approx(info.duration)
    assert info.has_audio
    assert info.width == 640
    assert info.height % 2 == 0 and info.height > 0


@needs_ffmpeg
@needs_demo
def test_render_preview_original_mode(tmp_path):
    out = tmp_path / "original.mp4"
    result = render_preview(demo_plan(), str(out), audio="original")
    assert out.is_file()
    assert probe(out).has_audio
    assert result["duration"] == pytest.approx(6.0, abs=0.3)


@needs_ffmpeg
@needs_demo
def test_render_preview_mix_mode(tmp_path):
    out = tmp_path / "mix.mp4"
    result = render_preview(demo_plan(), str(out), audio="mix")
    assert out.is_file()
    assert probe(out).has_audio
    assert result["duration"] == pytest.approx(6.0, abs=0.3)


@needs_ffmpeg
@needs_demo
def test_progress_callback_counts_to_total(tmp_path):
    calls: list[tuple[int, int, str]] = []
    render_preview(
        demo_plan(),
        str(tmp_path / "p.mp4"),
        progress=lambda done, total, label: calls.append((done, total, label)),
    )
    assert calls, "progress was never called"
    totals = {total for _, total, _ in calls}
    assert totals == {5}  # 4 segments + the final mux
    assert [done for done, _, _ in calls] == list(range(1, 6))
    assert calls[-1][0] == calls[-1][1]


# ------------------------------------------------------------ thumbnails


@needs_ffmpeg
@needs_demo
def test_extract_thumbnail_jpeg(tmp_path):
    out = tmp_path / "thumb.jpg"
    returned = extract_thumbnail(str(DEMO / "clip_A.mp4"), 2.0, str(out), width=320)
    assert returned == str(out)
    assert out.is_file() and out.stat().st_size > 1000  # a real image, not a stub


@needs_ffmpeg
@needs_demo
def test_extract_thumbnail_png(tmp_path):
    out = tmp_path / "thumb.png"
    extract_thumbnail(str(DEMO / "clip_B.mp4"), 5.0, str(out), width=160)
    assert out.is_file() and out.stat().st_size > 1000
    assert out.read_bytes()[:8] == b"\x89PNG\r\n\x1a\n"


@needs_ffmpeg
def test_extract_thumbnail_bad_path_raises(tmp_path):
    with pytest.raises(MonteurMediaError):
        extract_thumbnail(
            str(tmp_path / "no_such_clip.mp4"), 1.0, str(tmp_path / "t.jpg")
        )


# ------------------------------------------------------------ robustness


@needs_ffmpeg
@needs_demo
def test_failed_render_leaves_no_temp_dir(tmp_path, monkeypatch):
    """A mid-render ffmpeg failure must still remove the segment dir."""
    workdir = tmp_path / "work"
    workdir.mkdir()
    real_mkdtemp = tempfile.mkdtemp
    monkeypatch.setattr(
        preview.tempfile,
        "mkdtemp",
        lambda prefix="", **kw: real_mkdtemp(prefix=prefix, dir=str(workdir)),
    )
    plan = demo_plan()
    plan.entries[1].clip_path = str(tmp_path / "missing.mp4")  # fails mid-render
    with pytest.raises(MonteurMediaError):
        render_preview(plan, str(tmp_path / "broken.mp4"))
    assert list(workdir.iterdir()) == []  # no leftover monteur-preview-* dirs


@needs_ffmpeg
@needs_demo
def test_successful_render_leaves_no_temp_dir(tmp_path, monkeypatch):
    workdir = tmp_path / "work"
    workdir.mkdir()
    real_mkdtemp = tempfile.mkdtemp
    monkeypatch.setattr(
        preview.tempfile,
        "mkdtemp",
        lambda prefix="", **kw: real_mkdtemp(prefix=prefix, dir=str(workdir)),
    )
    render_preview(demo_plan(), str(tmp_path / "ok.mp4"))
    assert list(workdir.iterdir()) == []
