"""Tests for monteur.preview — the no-Resolve preview + export renderers.

End-to-end against the synthetic demo footage (tests/.demo-footage,
generated by make_demo_footage.py; skipped when missing) plus pure
validation tests that need neither footage nor ffmpeg.
"""

from __future__ import annotations

import math
import struct
import tempfile
import wave
from pathlib import Path

import pytest

from _demo import DEMO
from monteur.media import MonteurMediaError, probe
from monteur.montage import MontageEntry, MontagePlan, SfxCue
from monteur import preview
from monteur.preview import extract_thumbnail, render_export, render_preview

try:
    import imageio_ffmpeg  # noqa: F401

    HAVE_FFMPEG = True
except ImportError:
    import shutil as _shutil

    HAVE_FFMPEG = bool(_shutil.which("ffmpeg"))

needs_ffmpeg = pytest.mark.skipif(not HAVE_FFMPEG, reason="ffmpeg not available")
needs_demo = pytest.mark.skipif(
    not (DEMO / "clip_A.mp4").exists(), reason="demo footage not present"
)


def demo_plan(music: bool = True) -> MontagePlan:
    """A tiny 6 s plan: three entries with a 0.4 s record gap (black dip)."""
    entries = [
        MontageEntry(
            clip_path=str(DEMO / "clip_A.mp4"),
            source_start=1.0, source_end=3.0,
            record_start=0.0, record_end=2.0, score=1.0,
        ),
        # record gap 2.0..2.4 — the smash-to-black dip
        MontageEntry(
            clip_path=str(DEMO / "clip_C.mp4"),
            source_start=2.0, source_end=4.0,
            record_start=2.4, record_end=4.4, score=0.9,
        ),
        MontageEntry(
            clip_path=str(DEMO / "clip_D.mp4"),
            source_start=0.5, source_end=2.1,
            record_start=4.4, record_end=6.0, score=0.8,
        ),
    ]
    return MontagePlan(
        music_path=str(DEMO / "song.wav") if music else "",
        duration=6.0,
        music_start=8.0 if music else 0.0,
        song_duration=60.0 if music else 0.0,
        fade_in=0.2,
        fade_out=0.5,
        entries=entries,
        dips=[(2.0, 0.4)],
    )


# ------------------------------------------------------------ validation


def test_unknown_audio_mode_raises():
    with pytest.raises(ValueError, match="unknown audio mode"):
        render_preview(demo_plan(), "out.mp4", audio="karaoke")


@pytest.mark.parametrize("mode", ["music", "mix"])
def test_music_modes_without_music_raise(mode):
    with pytest.raises(ValueError, match="plan has no music"):
        render_preview(demo_plan(music=False), "out.mp4", audio=mode)


def test_empty_plan_raises():
    plan = MontagePlan(music_path=str(DEMO / "song.wav"), duration=6.0)
    with pytest.raises(ValueError, match="no entries"):
        render_preview(plan, "out.mp4")


# ------------------------------------------------------------ rendering


@needs_ffmpeg
@needs_demo
def test_render_preview_music_mode(tmp_path):
    out = tmp_path / "preview.mp4"
    result = render_preview(demo_plan(), str(out), width=640, audio="music")
    assert out.is_file() and out.stat().st_size > 0
    assert result["path"] == str(out)
    assert result["segments"] == 4  # 3 entries + 1 black dip
    assert result["width"] == 640
    info = probe(out)
    assert info.duration == pytest.approx(6.0, abs=0.3)
    assert result["duration"] == pytest.approx(info.duration)
    assert info.has_audio
    assert info.width == 640
    assert info.height % 2 == 0 and info.height > 0


@needs_ffmpeg
@needs_demo
def test_render_preview_original_mode(tmp_path):
    out = tmp_path / "original.mp4"
    result = render_preview(demo_plan(), str(out), audio="original")
    assert out.is_file()
    assert probe(out).has_audio
    assert result["duration"] == pytest.approx(6.0, abs=0.3)


@needs_ffmpeg
@needs_demo
def test_render_preview_mix_mode(tmp_path):
    out = tmp_path / "mix.mp4"
    result = render_preview(demo_plan(), str(out), audio="mix")
    assert out.is_file()
    assert probe(out).has_audio
    assert result["duration"] == pytest.approx(6.0, abs=0.3)


@needs_ffmpeg
@needs_demo
def test_progress_callback_counts_to_total(tmp_path):
    calls: list[tuple[int, int, str]] = []
    render_preview(
        demo_plan(),
        str(tmp_path / "p.mp4"),
        progress=lambda done, total, label: calls.append((done, total, label)),
    )
    assert calls, "progress was never called"
    totals = {total for _, total, _ in calls}
    assert totals == {5}  # 4 segments + the final mux
    assert [done for done, _, _ in calls] == list(range(1, 6))
    assert calls[-1][0] == calls[-1][1]


# ------------------------------------------------------------ thumbnails


@needs_ffmpeg
@needs_demo
def test_extract_thumbnail_jpeg(tmp_path):
    out = tmp_path / "thumb.jpg"
    returned = extract_thumbnail(str(DEMO / "clip_A.mp4"), 2.0, str(out), width=320)
    assert returned == str(out)
    assert out.is_file() and out.stat().st_size > 1000  # a real image, not a stub


@needs_ffmpeg
@needs_demo
def test_extract_thumbnail_png(tmp_path):
    out = tmp_path / "thumb.png"
    extract_thumbnail(str(DEMO / "clip_B.mp4"), 5.0, str(out), width=160)
    assert out.is_file() and out.stat().st_size > 1000
    assert out.read_bytes()[:8] == b"\x89PNG\r\n\x1a\n"


@needs_ffmpeg
def test_extract_thumbnail_bad_path_raises(tmp_path):
    with pytest.raises(MonteurMediaError):
        extract_thumbnail(
            str(tmp_path / "no_such_clip.mp4"), 1.0, str(tmp_path / "t.jpg")
        )


# ------------------------------------------------------------ robustness


@needs_ffmpeg
@needs_demo
def test_failed_render_leaves_no_temp_dir(tmp_path, monkeypatch):
    """A mid-render ffmpeg failure must still remove the segment dir."""
    workdir = tmp_path / "work"
    workdir.mkdir()
    real_mkdtemp = tempfile.mkdtemp
    monkeypatch.setattr(
        preview.tempfile,
        "mkdtemp",
        lambda prefix="", **kw: real_mkdtemp(prefix=prefix, dir=str(workdir)),
    )
    plan = demo_plan()
    plan.entries[1].clip_path = str(tmp_path / "missing.mp4")  # fails mid-render
    with pytest.raises(MonteurMediaError):
        render_preview(plan, str(tmp_path / "broken.mp4"))
    assert list(workdir.iterdir()) == []  # no leftover monteur-preview-* dirs


@needs_ffmpeg
@needs_demo
def test_successful_render_leaves_no_temp_dir(tmp_path, monkeypatch):
    workdir = tmp_path / "work"
    workdir.mkdir()
    real_mkdtemp = tempfile.mkdtemp
    monkeypatch.setattr(
        preview.tempfile,
        "mkdtemp",
        lambda prefix="", **kw: real_mkdtemp(prefix=prefix, dir=str(workdir)),
    )
    render_preview(demo_plan(), str(tmp_path / "ok.mp4"))
    assert list(workdir.iterdir()) == []


# ============================================================ render_export
#
# The Direct Export engine. Tests render at a tiny explicit `size` (the
# documented advanced/testing override) — canvas presets are delivery
# resolutions and far too big for a test suite.


def _tiny_wav(path: Path, seconds: float = 0.5) -> str:
    """A short decaying 440 Hz ping — a stand-in for a placed SFX file."""
    rate = 44100
    n = int(seconds * rate)
    with wave.open(str(path), "wb") as fh:
        fh.setnchannels(1)
        fh.setsampwidth(2)
        fh.setframerate(rate)
        fh.writeframes(
            b"".join(
                struct.pack(
                    "<h",
                    int(
                        20000
                        * math.sin(2 * math.pi * 440 * i / rate)
                        * math.exp(-i / (rate * 0.2))
                    ),
                )
                for i in range(n)
            )
        )
    return str(path)


def _titles_expected_to_draw() -> bool:
    """Whether THIS environment can draw act titles (filter + font)."""
    return preview._supports_drawtext() and preview._find_font() is not None


# ------------------------------------------------------------ validation


def test_export_unknown_audio_mode_raises():
    with pytest.raises(ValueError, match="unknown audio mode"):
        render_export(demo_plan(), "out.mp4", audio="karaoke")


def test_export_music_mode_without_music_raises():
    with pytest.raises(ValueError, match="plan has no music"):
        render_export(demo_plan(music=False), "out.mp4", audio="music")


def test_export_empty_plan_raises():
    plan = MontagePlan(music_path=str(DEMO / "song.wav"), duration=6.0)
    with pytest.raises(ValueError, match="no entries"):
        render_export(plan, "out.mp4")


def test_export_unknown_quality_raises():
    with pytest.raises(ValueError, match="unknown quality"):
        render_export(demo_plan(), "out.mp4", quality="ultra")


def test_export_unknown_canvas_raises():
    with pytest.raises(ValueError, match="unknown canvas"):
        render_export(demo_plan(), "out.mp4", canvas="imax")


# ------------------------------------------------------------ filter graphs
#
# The graph builders are pure functions — the loudnorm finish, the mix
# levels and the xfade chaining are asserted on the constructed graphs.


def test_export_audio_graph_finishes_with_loudnorm():
    graph = preview._export_audio_graph(
        "music", "1:a", None, [], 0.0, 0.0, 6.0
    )
    assert "loudnorm=I=-14:TP=-1:LRA=11" in graph
    assert graph.endswith("[a]")
    # loudnorm upsamples internally; the chain resamples back after it
    assert graph.index("loudnorm") < graph.index("aresample=48000")


def test_export_audio_graph_mix_levels_and_sfx():
    graph = preview._export_audio_graph(
        "mix", "4:a", "5:a", [("6:a", 2.0, 0.5)], 0.2, 0.5, 6.0
    )
    assert "volume=1" in graph and "volume=0.6" in graph  # the fixed mix
    assert "atrim=0:0.500" in graph  # trimmed to min(cue, file)
    assert "adelay=2000|2000" in graph  # placed at cue.time
    assert "normalize=0" in graph
    assert "afade=t=in:st=0:d=0.200" in graph
    assert "afade=t=out:st=5.500:d=0.500" in graph
    # the fades run BEFORE the loudness finish
    assert graph.index("afade") < graph.index("loudnorm")


def test_export_video_graph_chains_xfade_and_concat():
    # segment 1 dissolves in (0.4s), segment 2 is a hard cut; segment 0
    # was rendered 0.4s long to feed the overlap.
    graph = preview._export_video_graph(
        [2.4, 2.0, 2.0], [0.0, 0.4, 0.0], 0.2, 0.5, 6.0
    )
    # the xfade offset is the incoming segment's record position: the
    # timeline timing never moves (2.4 rendered - 0.4 overlap = 2.0)
    assert "xfade=transition=fade:duration=0.400:offset=2.000" in graph
    assert "concat=n=2:v=1:a=0" in graph
    assert "fade=t=in:st=0:d=0.200" in graph
    assert "fade=t=out:st=5.500:d=0.500" in graph
    assert graph.endswith("[v]")


def test_export_video_graph_hard_cuts_only():
    graph = preview._export_video_graph([2.0, 2.0], [0.0, 0.0], 0.0, 0.0, 4.0)
    assert "xfade" not in graph
    assert "concat=n=2:v=1:a=0" in graph


# ------------------------------------------------------------ rendering


@needs_ffmpeg
@needs_demo
def test_render_export_high_profile(tmp_path):
    out = tmp_path / "export.mp4"
    result = render_export(
        demo_plan(), str(out), size=(480, 270), audio="music", quality="high"
    )
    assert out.is_file() and out.stat().st_size > 0
    assert result["path"] == str(out)
    assert result["width"] == 480 and result["height"] == 270
    assert result["seconds"] > 0
    assert result["notes"] == []  # nothing degraded in this plan
    info = probe(out)
    assert info.duration == pytest.approx(6.0, abs=0.3)
    assert result["duration"] == pytest.approx(info.duration)
    assert info.width == 480 and info.height == 270
    assert info.has_audio
    # +faststart: the moov atom sits BEFORE the media data (YouTube-friendly)
    data = out.read_bytes()
    assert 0 < data.find(b"moov") < data.find(b"mdat")


@needs_ffmpeg
@needs_demo
def test_render_preview_no_music_original_carries_sound(tmp_path):
    # Field bug: no-music builds lost their sound. The preview of a plan
    # without a song renders the clips' own audio.
    out = tmp_path / "nomusic.mp4"
    result = render_preview(demo_plan(music=False), str(out), audio="original")
    assert out.is_file()
    assert probe(out).has_audio
    assert result["duration"] == pytest.approx(6.0, abs=0.3)


@needs_ffmpeg
@needs_demo
def test_render_preview_with_music_window(tmp_path):
    # A delayed music entry renders: bed trimmed/delayed, still 6s long.
    plan = demo_plan()
    plan.music_in = 2.0
    plan.music_out = 5.0
    out = tmp_path / "windowed.mp4"
    result = render_preview(plan, str(out), audio="music")
    assert out.is_file()
    info = probe(out)
    assert info.has_audio
    assert result["duration"] == pytest.approx(info.duration)
    assert info.duration == pytest.approx(6.0, abs=0.3)


@needs_ffmpeg
@needs_demo
def test_render_export_no_music_with_placed_sfx(tmp_path):
    # The full no-music program: clips' own sound bed + a placed SFX file
    # mixed on top, no song anywhere.
    plan = demo_plan(music=False)
    plan.sfx = [
        SfxCue(1.0, 0.5, "impact", "hit", "on the cut",
               file=_tiny_wav(tmp_path / "hit.wav")),
    ]
    out = tmp_path / "nomusic_export.mp4"
    result = render_export(
        plan, str(out), size=(320, 180), audio="original", quality="medium"
    )
    assert out.is_file()
    assert result["notes"] == []  # the SFX file exists and was mixed in
    assert probe(out).has_audio


@needs_ffmpeg
@needs_demo
def test_render_export_with_music_window(tmp_path):
    plan = demo_plan()
    plan.music_in = 2.0
    out = tmp_path / "windowed_export.mp4"
    result = render_export(
        plan, str(out), size=(320, 180), audio="music", quality="medium"
    )
    assert out.is_file()
    assert result["notes"] == []
    info = probe(out)
    assert info.has_audio
    assert info.duration == pytest.approx(6.0, abs=0.3)


@needs_ffmpeg
@needs_demo
def test_render_export_size_override_is_forced_even(tmp_path):
    out = tmp_path / "odd.mp4"
    result = render_export(
        demo_plan(), str(out), size=(479, 269), audio="original",
        quality="medium",
    )
    assert result["width"] % 2 == 0 and result["height"] % 2 == 0
    info = probe(out)
    assert (info.width, info.height) == (result["width"], result["height"])


@needs_ffmpeg
@needs_demo
def test_render_export_canvas_preset_sets_the_resolution(tmp_path, monkeypatch):
    # Canvas presets are real delivery sizes (uhd is 3840x2160) — patch a
    # tiny one in so the preset path stays testable at test speed.
    import monteur.montage as montage

    monkeypatch.setitem(montage.CANVASES, "tiny-test", (320, 180))
    out = tmp_path / "canvas.mp4"
    result = render_export(
        demo_plan(), str(out), canvas="tiny-test", audio="music",
        quality="medium",
    )
    info = probe(out)
    assert (info.width, info.height) == (320, 180)
    assert (result["width"], result["height"]) == (320, 180)


@needs_ffmpeg
@needs_demo
def test_render_export_dissolve_with_handles(tmp_path):
    """A transition whose outgoing clip has source handles: a real xfade,
    no degradation note, and the timeline duration unchanged."""
    plan = demo_plan()
    # entry 2 (clip_D at 4.4s) dissolves in; the outgoing clip_C entry has
    # source 2.0..4.0 of an 8s file — plenty of handle material.
    plan.entries[2].transition = 0.4
    plan.entries[1].clip_duration = 8.0
    out = tmp_path / "dissolve.mp4"
    result = render_export(plan, str(out), size=(320, 180), audio="music")
    assert result["notes"] == []
    assert result["duration"] == pytest.approx(6.0, abs=0.3)


@needs_ffmpeg
@needs_demo
def test_render_export_dissolve_without_handles_is_a_noted_hard_cut(tmp_path):
    plan = demo_plan()
    plan.entries[2].transition = 0.4
    # the outgoing clip_C entry ends exactly at its file's end: no handles
    plan.entries[1].clip_duration = 4.0
    out = tmp_path / "hardcut.mp4"
    result = render_export(plan, str(out), size=(320, 180), audio="music")
    assert any("hard cut" in note for note in result["notes"])
    assert result["duration"] == pytest.approx(6.0, abs=0.3)


@needs_ffmpeg
@needs_demo
def test_render_export_dissolve_out_of_a_black_dip_always_works(tmp_path):
    """Black has unlimited handles — a dissolve out of a dip never
    degrades, whatever the surrounding clips' durations."""
    plan = demo_plan()
    plan.entries[1].transition = 0.3  # clip_C enters from the 2.0..2.4 dip
    out = tmp_path / "fromblack.mp4"
    result = render_export(plan, str(out), size=(320, 180), audio="music")
    assert result["notes"] == []
    assert result["duration"] == pytest.approx(6.0, abs=0.3)


@needs_ffmpeg
@needs_demo
def test_render_export_titles_on_the_dips(tmp_path):
    plan = demo_plan()
    plan.title_texts = ["Chapter One"]
    out = tmp_path / "titled.mp4"
    result = render_export(plan, str(out), size=(320, 180), audio="music")
    assert out.is_file()  # a title must NEVER fail the export
    if _titles_expected_to_draw():
        # drawn for real: no degradation note anywhere
        assert not any("titles were skipped" in n for n in result["notes"])
    else:
        # no drawtext filter or no font: skipped WITH an honest note
        assert any("titles were skipped" in n for n in result["notes"])


@needs_ffmpeg
@needs_demo
def test_render_export_mixes_placed_sfx(tmp_path):
    plan = demo_plan()
    plan.sfx = [
        SfxCue(
            time=2.0, duration=0.5, kind="impact", query="impact hit",
            note="on the dip", file=_tiny_wav(tmp_path / "hit.wav"),
        )
    ]
    out = tmp_path / "sfx.mp4"
    result = render_export(plan, str(out), size=(320, 180), audio="music")
    assert out.is_file()
    assert not any("missing" in note for note in result["notes"])
    assert probe(out).has_audio


@needs_ffmpeg
@needs_demo
def test_render_export_missing_sfx_file_is_a_note(tmp_path):
    plan = demo_plan()
    plan.sfx = [
        SfxCue(
            time=2.0, duration=0.5, kind="impact", query="impact",
            note="gone", file=str(tmp_path / "no_such.wav"),
        )
    ]
    out = tmp_path / "sfxless.mp4"
    result = render_export(plan, str(out), size=(320, 180), audio="music")
    assert out.is_file()
    assert any("sound element missing" in note for note in result["notes"])


@needs_ffmpeg
@needs_demo
@pytest.mark.parametrize("mode", ["original", "mix"])
def test_render_export_own_sound_modes(tmp_path, mode):
    out = tmp_path / f"{mode}.mp4"
    result = render_export(demo_plan(), str(out), size=(320, 180), audio=mode)
    assert probe(out).has_audio
    assert result["duration"] == pytest.approx(6.0, abs=0.3)


@needs_ffmpeg
@needs_demo
def test_render_export_progress_stages(tmp_path):
    calls: list[tuple[int, int, str]] = []
    render_export(
        demo_plan(),
        str(tmp_path / "p.mp4"),
        size=(320, 180),
        audio="mix",
        progress=lambda done, total, label: calls.append((done, total, label)),
    )
    # 4 segments + the original-sound bed + the final transitions/mux pass
    totals = {total for _, total, _ in calls}
    assert totals == {6}
    assert [done for done, _, _ in calls] == list(range(1, 7))
    labels = [label for _, _, label in calls]
    assert labels[-1] == "mux"
    assert labels[-2] == "audio bed"
    assert "black" in labels  # the dip segment ticked too


@needs_ffmpeg
@needs_demo
def test_failed_export_leaves_no_temp_dir(tmp_path, monkeypatch):
    workdir = tmp_path / "work"
    workdir.mkdir()
    real_mkdtemp = tempfile.mkdtemp
    monkeypatch.setattr(
        preview.tempfile,
        "mkdtemp",
        lambda prefix="", **kw: real_mkdtemp(prefix=prefix, dir=str(workdir)),
    )
    plan = demo_plan()
    plan.entries[1].clip_path = str(tmp_path / "missing.mp4")
    with pytest.raises(MonteurMediaError):
        render_export(plan, str(tmp_path / "broken.mp4"), size=(320, 180))
    assert list(workdir.iterdir()) == []


@needs_ffmpeg
@needs_demo
def test_successful_export_leaves_no_temp_dir(tmp_path, monkeypatch):
    workdir = tmp_path / "work"
    workdir.mkdir()
    real_mkdtemp = tempfile.mkdtemp
    monkeypatch.setattr(
        preview.tempfile,
        "mkdtemp",
        lambda prefix="", **kw: real_mkdtemp(prefix=prefix, dir=str(workdir)),
    )
    render_export(demo_plan(), str(tmp_path / "ok.mp4"), size=(320, 180))
    assert list(workdir.iterdir()) == []


# ------------------------------------------------------------ music through the dip
#
# Field bug hunt: "during the title cards there is NO sound at all". The
# renderers must keep the SONG playing through a smash-to-black dip (the
# music carries the title card); "original" mode is silent there by
# design. Measured for real: RMS level of the rendered audio inside the
# dip window vs. the body.


def _rms_db(path: str, start: float, end: float) -> float:
    """Mean RMS level (dB) of the audio between start and end; -inf = silence."""
    import re
    import subprocess

    from monteur.media import find_ffmpeg

    out = subprocess.run(
        [
            find_ffmpeg(), "-hide_banner", "-i", str(path),
            "-af", f"atrim={start}:{end},astats=metadata=1:reset=0",
            "-f", "null", "-",
        ],
        capture_output=True,
    ).stderr.decode("utf-8", "replace")
    match = re.search(r"RMS level dB:\s*(-?[\d.]+|-inf)", out)
    assert match, f"no astats RMS in ffmpeg output for {path}"
    return float("-inf") if match.group(1) == "-inf" else float(match.group(1))


@needs_ffmpeg
@needs_demo
@pytest.mark.parametrize("mode", ["music", "mix"])
def test_preview_music_plays_through_the_dip(tmp_path, mode):
    out = tmp_path / f"dip_{mode}.mp4"
    render_preview(demo_plan(), str(out), audio=mode)
    # the dip is 2.0..2.4; the song must still be audible inside it
    assert _rms_db(out, 2.05, 2.35) > -60.0


@needs_ffmpeg
@needs_demo
def test_preview_original_mode_is_silent_in_the_dip_by_design(tmp_path):
    out = tmp_path / "dip_original.mp4"
    render_preview(demo_plan(), str(out), audio="original")
    assert _rms_db(out, 2.05, 2.35) == float("-inf")
    assert _rms_db(out, 1.0, 1.5) > -60.0  # the body carries the clip sound


@needs_ffmpeg
@needs_demo
@pytest.mark.parametrize("mode", ["music", "mix"])
def test_export_music_plays_through_the_dip(tmp_path, mode):
    out = tmp_path / f"dip_export_{mode}.mp4"
    render_export(demo_plan(), str(out), size=(320, 180), audio=mode,
                  quality="medium")
    assert _rms_db(out, 2.05, 2.35) > -60.0


@needs_ffmpeg
@needs_demo
def test_export_original_dip_is_silent_but_the_braam_lands(tmp_path):
    # "original" mode: the dip itself is silent, but a placed SFX element
    # cue AT the dip still hits — the braam that carries the title.
    plan = demo_plan()
    plan.sfx = [
        SfxCue(time=2.0, duration=0.4, kind="sub-drop", query="sub drop boom",
               note="title slot", file=_tiny_wav(tmp_path / "boom.wav", 0.4)),
    ]
    out = tmp_path / "dip_braam.mp4"
    result = render_export(plan, str(out), size=(320, 180), audio="original",
                           quality="medium")
    assert result["notes"] == []
    assert _rms_db(out, 2.05, 2.35) > -60.0  # the braam is audible in the dip
